In [10]:
import spgci as ci
from datetime import date
import pandas as pd

In [2]:
mdd = ci.MarketData()

In [3]:
symbols = ['RCUST04', 'RCCNT04', 'RCGMT04', 'RCUSL04', 'RCUSO04', 'RCUSG04', 'RCUSI04', 'RCUSM04', 'RCUSV04', 'RCUSD04', 'RCUSH04']

In [4]:
mdd.get_assessments_by_symbol_current(symbol=symbols)

   bate assessDate  value isCorrected             modDate   symbol
0     u 2023-03-31    139           N 2023-03-31 17:06:21  RCCNT04
1     u 2023-03-31     17           N 2023-03-31 17:06:21  RCGMT04
2     u 2023-03-31     51           N 2023-03-31 17:06:21  RCUSD04
3     u 2023-03-31    160           N 2023-03-31 17:06:21  RCUSG04
4     u 2023-03-31    691           N 2023-03-31 17:06:21  RCUSH04
5     u 2023-03-31    592           N 2023-03-31 17:06:21  RCUSI04
6     u 2023-03-31    737           N 2023-03-31 17:06:21  RCUSL04
7     u 2023-03-31      3           N 2023-03-31 17:06:21  RCUSM04
8     u 2023-03-31     18           N 2023-03-31 17:06:21  RCUSO04
9     u 2023-03-31    755           N 2023-03-31 17:06:21  RCUST04
10    u 2023-03-31     13           N 2023-03-31 17:06:21  RCUSV04

In [5]:
ref = mdd.get_symbols(symbol=symbols)
ref.head()

,symbol,description,assessment_frequency,bate_code,holiday_schedule,commodity,currency,exchange,publication_frequency_code,mdc_description,mdc,delivery_region,delivery_region_basis,active,uom
0,RCUSL04,BH RigCt Land United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
1,RCUSH04,BH RigCt Horizontal United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
2,RCUSD04,BH RigCt Directional United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
3,RCUSM04,BH RigCt Misc United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
4,RCUSI04,BH RigCt Oil United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS

In [6]:
mdd.get_assessments_by_symbol_historical(symbol='RCUST04',)

     bate  value assessDate isCorrected             modDate   symbol
0       u   1029 1990-01-05           N 2010-04-01 00:00:00  RCUST04
1       u   1019 1990-01-12           N 2010-04-01 00:00:00  RCUST04
2       u    964 1990-01-19           N 2010-04-01 00:00:00  RCUST04
3       u    937 1990-01-26           N 2010-04-01 00:00:00  RCUST04
4       u    931 1990-02-02           N 2010-04-01 00:00:00  RCUST04
...   ...    ...        ...         ...                 ...      ...
1718    u    753 2023-02-24           N 2023-02-24 18:08:35  RCUST04
1719    u    746 2023-03-10           N 2023-03-10 18:09:15  RCUST04
1720    u    754 2023-03-17           N 2023-03-17 17:50:59  RCUST04
1721    u    758 2023-03-24           N 2023-03-24 17:07:44  RCUST04
1722    u    755 2023-03-31           N 2023-03-31 17:06:21  RCUST04

[1723 rows x 6 columns]

In [58]:
df = mdd.get_assessments_by_symbol_historical(assess_date_gte=date(2022,1,1), symbol=symbols).sort_values("assessDate", ascending=False).reset_index(drop=True)
df.head()

  bate  value assessDate isCorrected             modDate   symbol
0    u     13 2023-03-31           N 2023-03-31 17:06:21  RCUSV04
1    u     51 2023-03-31           N 2023-03-31 17:06:21  RCUSD04
2    u     17 2023-03-31           N 2023-03-31 17:06:21  RCGMT04
3    u    737 2023-03-31           N 2023-03-31 17:06:21  RCUSL04
4    u    160 2023-03-31           N 2023-03-31 17:06:21  RCUSG04

In [83]:
df = df.merge(ref, on='symbol')
df.head()

,bate,value,assessDate,isCorrected,modDate,symbol,description,assessment_frequency,bate_code,holiday_schedule,commodity,currency,exchange,publication_frequency_code,mdc_description,mdc,delivery_region,delivery_region_basis,active,uom
0,u,13,2023-03-31,N,2023-03-31 17:06:21,RCUSV04,BH RigCt Vertical United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
1,u,16,2023-03-24,N,2023-03-24 17:07:44,RCUSV04,BH RigCt Vertical United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
2,u,15,2023-03-17,N,2023-03-17 17:50:59,RCUSV04,BH RigCt Vertical United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
3,u,12,2023-03-10,N,2023-03-10 18:09:15,RCUSV04,BH RigCt Vertical United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
4,u,16,2023-02-24,N,2023-02-24 18:08:35,RCUSV04,BH RigCt Vertical United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS

In [91]:
filt = df['assessDate'].isin(df.drop_duplicates("assessDate").reset_index(drop=True).iloc[:2]['assessDate'])
latest_df = df[filt]
latest_df.head()

,bate,value,assessDate,isCorrected,modDate,symbol,description,assessment_frequency,bate_code,holiday_schedule,commodity,currency,exchange,publication_frequency_code,mdc_description,mdc,delivery_region,delivery_region_basis,active,uom
0,u,13,2023-03-31,N,2023-03-31 17:06:21,RCUSV04,BH RigCt Vertical United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
1,u,16,2023-03-24,N,2023-03-24 17:07:44,RCUSV04,BH RigCt Vertical United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
62,u,51,2023-03-31,N,2023-03-31 17:06:21,RCUSD04,BH RigCt Directional United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
63,u,50,2023-03-24,N,2023-03-24 17:07:44,RCUSD04,BH RigCt Directional United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
124,u,17,2023-03-31,N,2023-03-31 17:06:21,RCGMT04,BH RigCt Gulf of Mexico Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],North America,North America,Active - Public,UNS

In [92]:
year_ago = df['assessDate'].max() - pd.DateOffset(years=1)
filt = df['assessDate'] >= year_ago
filt2 = df["assessDate"] == df[filt]['assessDate'].min()
year_ago_df = df[filt2]
year_ago_df.head()

,bate,value,assessDate,isCorrected,modDate,symbol,description,assessment_frequency,bate_code,holiday_schedule,commodity,currency,exchange,publication_frequency_code,mdc_description,mdc,delivery_region,delivery_region_basis,active,uom
50,u,25,2022-04-01,N,2022-04-01 17:03:49,RCUSV04,BH RigCt Vertical United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
112,u,35,2022-04-01,N,2022-04-01 17:03:49,RCUSD04,BH RigCt Directional United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
174,u,14,2022-04-01,N,2022-04-01 17:03:49,RCGMT04,BH RigCt Gulf of Mexico Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],North America,North America,Active - Public,UNS
236,u,659,2022-04-01,N,2022-04-01 17:03:49,RCUSL04,BH RigCt Land United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
298,u,138,2022-04-01,N,2022-04-01 17:03:49,RCUSG04,BH RigCt Gas United States Wkly,Weekly,[u],CALUS00,Natural gas,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS

In [86]:
concat = pd.concat([latest_df, year_ago_df]).reset_index(drop=True)
concat.head()

,bate,value,assessDate,isCorrected,modDate,symbol,description,assessment_frequency,bate_code,holiday_schedule,commodity,currency,exchange,publication_frequency_code,mdc_description,mdc,delivery_region,delivery_region_basis,active,uom
0,u,13,2023-03-31,N,2023-03-31 17:06:21,RCUSV04,BH RigCt Vertical United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
1,u,16,2023-03-24,N,2023-03-24 17:07:44,RCUSV04,BH RigCt Vertical United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
2,u,51,2023-03-31,N,2023-03-31 17:06:21,RCUSD04,BH RigCt Directional United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
3,u,50,2023-03-24,N,2023-03-24 17:07:44,RCUSD04,BH RigCt Directional United States Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],United States,United States,Active - Public,UNS
4,u,17,2023-03-31,N,2023-03-31 17:06:21,RCGMT04,BH RigCt Gulf of Mexico Wkly,Weekly,[u],CALUS00,Crude oil,UNS,Baker Hughes,WA,[Statistics: Baker Hughes Rig Counts],[IG],North America,North America,Active - Public,UNS

In [88]:
pt = concat.pivot_table(index=['description', 'symbol'], columns='assessDate', values='value').sort_values("assessDate", axis=1, ascending=False)
pt

,assessDate,2023-03-31,2023-03-24,2022-04-01
description,symbol,,,
BH RigCt Canada Wkly,RCCNT04,139,165,124
BH RigCt Directional United States Wkly,RCUSD04,51,50,35
BH RigCt Gas United States Wkly,RCUSG04,160,162,138
BH RigCt Gulf of Mexico Wkly,RCGMT04,17,17,14
BH RigCt Horizontal United States Wkly,RCUSH04,691,692,613
BH RigCt Land United States Wkly,RCUSL04,737,740,659
BH RigCt Misc United States Wkly,RCUSM04,3,3,2
BH RigCt Offshore United States Wkly,RCUSO04,18,18,14
BH RigCt Oil United States Wkly,RCUSI04,592,593,533
BH RigCt United States Wkly,RCUST04,755,758,673
BH RigCt Vertical United States Wkly,RCUSV04,13,16,25

In [89]:
pt['Change WoW'] = pt.iloc[:, 0] - pt.iloc[:, 1]

In [122]:
def sort_symbols(sym: str) -> int:
  d = { s: symbols.index(s) for s in sym}
  return d

In [124]:
pt.sort_values("symbol", key=sort_symbols)

,assessDate,2023-03-31 00:00:00,2023-03-24 00:00:00,2022-04-01 00:00:00,Change WoW
description,symbol,,,,
BH RigCt United States Wkly,RCUST04,755,758,673,-3
BH RigCt Canada Wkly,RCCNT04,139,165,124,-26
BH RigCt Gulf of Mexico Wkly,RCGMT04,17,17,14,0
BH RigCt Land United States Wkly,RCUSL04,737,740,659,-3
BH RigCt Offshore United States Wkly,RCUSO04,18,18,14,0
BH RigCt Gas United States Wkly,RCUSG04,160,162,138,-2
BH RigCt Oil United States Wkly,RCUSI04,592,593,533,-1
BH RigCt Misc United States Wkly,RCUSM04,3,3,2,0
BH RigCt Vertical United States Wkly,RCUSV04,13,16,25,-3
BH RigCt Directional United States Wkly,RCUSD04,51,50,35,1
BH RigCt Horizontal United States Wkly,RCUSH04,691,692,613,-1